- name: Install k8s and podman packages
  become: yes
  hosts: k8s
  roles:
    - podman
    - k8s-all

- name: Setup Master nodes
  become: yes
  hosts: master
  roles:
    - k8s-master

- name: Setup Worker nodes
  become: yes
  hosts: worker
  roles:
    - k8s-worker